[project]
name = "server-litestar"
version = "1.0.0"
description = "StaffSec"
requires-python = "==3.14"
dependencies = [
    "advanced-alchemy>=1.8.2",
    "asyncpg>=0.31.0",
    "bcrypt>=5.0.0",
    "granian>=2.7.1",
    "litestar[standard, jwt, pydantic, sqlalchemy]>=2.19.0",
    "python-dotenv>=1.2.1",
    "typer>=0.21.1",
]

[tool.ruff]
select = ["ALL"]
ignore = ["DTZ005", "PLC0415", "PLR2004", "RUF003", "RUF001", "TC001", "TC002"]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["D", "S101", "S311"]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
    "pytest-asyncio>=1.3.0",
]
