openapi: 3.0.0
info:
  title: "Flask REST API"
  description: "API для получения анкетных данных и результатов проверки"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /anketa:
    get:
      operationId: "app.api.api.anketa"
      tags:
        - "Анкета"
      summary: "Отправка анкеты на проверку в подразделение безопасности (пример не для отправки_"
      responses:
        "200":
          description: "Successfully received candidate resume"
          content:
            application/json:
              schema:
                type: object
              examples:
                success:
                  summary: JSON example
                  value:
                    {
                      "id": 123,
                      "resume": {
                        "full_name": "Семенов Владимир Викторович",
                        "last_name": "1996, Сидоров Владимир Викторович",
                        "birthday": "09-11-1980",
                        "birth_place": "г. Брянск",
                        "country": "Россия",
                        "snils": "34562345678",
                        "inn": "328765432109",
                        "education": "1998 г. - МГУ им Ломоносова, инженер"
                      },
                      "staff": {
                        "s_staff": "Начальник отдела",
                        "s_department": "Служба безопасности"
                      },
                      "passport": {
                        "p_series_passport": "4505",
                        "p_number_passport": "102345",
                        "p_agency": "ГУВД по г. Москве",
                        "p_date_given": "2005-11-20"
                      },
                      "address": [
                        {
                          "a_type": "Адрес регистрации",
                          "a_address": "г. Москва, ул. Скрябина, д. 18 кв. 1"
                        },
                        {
                          "a_type": "Адрес проживания",
                          "a_address": "г. Москва, ул. Скрябина, д. 18 кв. 1"
                        }
                      ],
                      "contact": [
                        {
                          "c_type": "Телефон",
                          "c_contact": "9348973456"
                        },
                        {
                          "c_type": "e-mail",
                          "c_contact": "test@gmail.com"
                        }
                      ],
                      "work": [
                        {
                          "w_period": "12.03.2008-04.04.2014",
                          "w_work_place": "ПАО 'Промсвязьбанк'",
                          "w_address": "г. Москва, ул. Вавиловаю д.1",
                          "w_staff": "ведущий специалист"
                        },
                        {
                          "w_period": "12.03.2014-04.04.2019",
                          "w_work_place": "ПАО 'ВТБ'",
                          "w_address": "г. Москва, ул. Вавиловаю д.1",
                          "w_staff": "ведущий специалист"
                        },
                        {
                          "w_period": "12.03.2018-",
                          "w_work_place": "ПАО 'МТС Банк'",
                          "w_address": "г. Москва, ул. Вавиловаю д.1",
                          "w_staff": "ведущий специалист"
                        }
                      ]
                    }

  /check:
    get:
      operationId: "app.api.api.check"
      tags:
        - "Проверка"
      summary: "Отправка результатов проверки в подразделение безопасности (пример не для отправки)"
      responses:
        "200":
          description: "Successfully received candidate check"
          content:
            application/json:
              schema:
                type: object
              examples:
                success:
                  summary: JSON example
                  value:
                    {
                      "id": 5,
                      "check_work_place": "",
                      "former_employee": "test",
                      "check_passport": "test",
                      "check_inn": "test",
                      "check_debt": "",
                      "check_bankruptcy": "test",
                      "check_bki": "test",
                      "check_court": "test",
                      "check_affiliation": "test",
                      "check_terrorist": "test",
                      "check_mvd": "test",
                      "check_internet": "",
                      "check_cronos": "",
                      "check_cross": "",
                      "check_addition": "",
                      "pfo": "",
                      "comment": "",
                      "resume": "",
                      "date_check": "",
                      "officer": "current_user",
                      "temp_path": "//cronosx1/",
                      "path": ""
                    }
