"""empty message

Revision ID: 403f79c348ed
Revises: 
Create Date: 2023-02-26 17:05:07.875048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403f79c348ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_region', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('address_type', sa.Text(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('region')
        batch_op.drop_column('address')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacts_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contacts_contact', sa.Text(), nullable=True))
        batch_op.drop_column('type')
        batch_op.drop_column('contact')

    with op.batch_alter_table('passports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_series_passport', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('passport_number_passport', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('passport_agency', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('passport_date_given', sa.Text(), nullable=True))
        batch_op.drop_column('number_passport')
        batch_op.drop_column('agency')
        batch_op.drop_column('series_passport')
        batch_op.drop_column('date_given')

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation_relation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relation_full_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relations_birthday', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relations_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relations_workplace', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relations_contact', sa.Text(), nullable=True))
        batch_op.drop_column('workplace')
        batch_op.drop_column('birthday')
        batch_op.drop_column('address')
        batch_op.drop_column('contact')
        batch_op.drop_column('full_name')
        batch_op.drop_column('relation')

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staffs_staff', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('staffs_department', sa.Text(), nullable=True))
        batch_op.drop_column('department')
        batch_op.drop_column('staff')

    with op.batch_alter_table('workplaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_period', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_work_place', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('work_staff', sa.Text(), nullable=True))
        batch_op.drop_column('period')
        batch_op.drop_column('work_place')
        batch_op.drop_column('address')
        batch_op.drop_column('staff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workplaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('work_place', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('period', sa.TEXT(), nullable=True))
        batch_op.drop_column('work_staff')
        batch_op.drop_column('work_address')
        batch_op.drop_column('work_work_place')
        batch_op.drop_column('work_period')

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('department', sa.TEXT(), nullable=True))
        batch_op.drop_column('staffs_department')
        batch_op.drop_column('staffs_staff')

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('full_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contact', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('birthday', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('workplace', sa.TEXT(), nullable=True))
        batch_op.drop_column('relations_contact')
        batch_op.drop_column('relations_workplace')
        batch_op.drop_column('relations_address')
        batch_op.drop_column('relations_birthday')
        batch_op.drop_column('relation_full_name')
        batch_op.drop_column('relation_relation')

    with op.batch_alter_table('passports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_given', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('series_passport', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('agency', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('number_passport', sa.TEXT(), nullable=True))
        batch_op.drop_column('passport_date_given')
        batch_op.drop_column('passport_agency')
        batch_op.drop_column('passport_number_passport')
        batch_op.drop_column('passport_series_passport')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.drop_column('contacts_contact')
        batch_op.drop_column('contacts_type')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('region', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.drop_column('address_type')
        batch_op.drop_column('address_address')
        batch_op.drop_column('address_region')

    # ### end Alembic commands ###
