"""empty message

Revision ID: af1d4dcf03b8
Revises: 403f79c348ed
Create Date: 2023-02-26 17:09:51.638940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af1d4dcf03b8'
down_revision = '403f79c348ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_staff', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('staff_department', sa.Text(), nullable=True))
        batch_op.drop_column('staffs_staff')
        batch_op.drop_column('staffs_department')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staffs_department', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('staffs_staff', sa.TEXT(), nullable=True))
        batch_op.drop_column('staff_department')
        batch_op.drop_column('staff_staff')

    # ### end Alembic commands ###
