"""empty message

Revision ID: b0fee276fbeb
Revises: f681b46fa0c3
Create Date: 2023-02-26 17:25:57.697495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0fee276fbeb'
down_revision = 'f681b46fa0c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('a_region', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('a_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('a_type', sa.Text(), nullable=True))
        batch_op.drop_column('address_region')
        batch_op.drop_column('address_address')
        batch_op.drop_column('address_type')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('c_contact', sa.Text(), nullable=True))
        batch_op.drop_column('contact_contact')
        batch_op.drop_column('contact_type')

    with op.batch_alter_table('passports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p_series_passport', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('p_number_passport', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('p_agency', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('p_date_given', sa.Text(), nullable=True))
        batch_op.drop_column('passport_agency')
        batch_op.drop_column('passport_series_passport')
        batch_op.drop_column('passport_date_given')
        batch_op.drop_column('passport_number_passport')

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('r_relation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('r_full_name', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('r_birthday', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('r_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('r_workplace', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('r_contact', sa.Text(), nullable=True))
        batch_op.drop_column('relation_workplace')
        batch_op.drop_column('relation_relation')
        batch_op.drop_column('relation_full_name')
        batch_op.drop_column('relation_birthday')
        batch_op.drop_column('relation_address')
        batch_op.drop_column('relation_contact')

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s_staff', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('s_department', sa.Text(), nullable=True))
        batch_op.drop_column('staff_department')
        batch_op.drop_column('staff_staff')

    with op.batch_alter_table('workplaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('w_period', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('w_work_place', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('w_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('w_staff', sa.Text(), nullable=True))
        batch_op.drop_column('work_work_place')
        batch_op.drop_column('work_address')
        batch_op.drop_column('work_period')
        batch_op.drop_column('work_staff')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workplaces', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_staff', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('work_period', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('work_address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('work_work_place', sa.TEXT(), nullable=True))
        batch_op.drop_column('w_staff')
        batch_op.drop_column('w_address')
        batch_op.drop_column('w_work_place')
        batch_op.drop_column('w_period')

    with op.batch_alter_table('staffs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('staff_staff', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('staff_department', sa.TEXT(), nullable=True))
        batch_op.drop_column('s_department')
        batch_op.drop_column('s_staff')

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation_contact', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relation_address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relation_birthday', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relation_full_name', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relation_relation', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relation_workplace', sa.TEXT(), nullable=True))
        batch_op.drop_column('r_contact')
        batch_op.drop_column('r_workplace')
        batch_op.drop_column('r_address')
        batch_op.drop_column('r_birthday')
        batch_op.drop_column('r_full_name')
        batch_op.drop_column('r_relation')

    with op.batch_alter_table('passports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passport_number_passport', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('passport_date_given', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('passport_series_passport', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('passport_agency', sa.TEXT(), nullable=True))
        batch_op.drop_column('p_date_given')
        batch_op.drop_column('p_agency')
        batch_op.drop_column('p_number_passport')
        batch_op.drop_column('p_series_passport')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contact_contact', sa.TEXT(), nullable=True))
        batch_op.drop_column('c_contact')
        batch_op.drop_column('c_type')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address_type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address_address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('address_region', sa.TEXT(), nullable=True))
        batch_op.drop_column('a_type')
        batch_op.drop_column('a_address')
        batch_op.drop_column('a_region')

    # ### end Alembic commands ###
