"""empty message

Revision ID: f681b46fa0c3
Revises: af1d4dcf03b8
Create Date: 2023-02-26 17:11:01.956135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f681b46fa0c3'
down_revision = 'af1d4dcf03b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_type', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('contact_contact', sa.Text(), nullable=True))
        batch_op.drop_column('contacts_contact')
        batch_op.drop_column('contacts_type')

    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relation_birthday', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relation_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relation_workplace', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('relation_contact', sa.Text(), nullable=True))
        batch_op.drop_column('relations_workplace')
        batch_op.drop_column('relations_birthday')
        batch_op.drop_column('relations_contact')
        batch_op.drop_column('relations_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relations_address', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relations_contact', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relations_birthday', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('relations_workplace', sa.TEXT(), nullable=True))
        batch_op.drop_column('relation_contact')
        batch_op.drop_column('relation_workplace')
        batch_op.drop_column('relation_address')
        batch_op.drop_column('relation_birthday')

    with op.batch_alter_table('contacts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contacts_type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('contacts_contact', sa.TEXT(), nullable=True))
        batch_op.drop_column('contact_contact')
        batch_op.drop_column('contact_type')

    # ### end Alembic commands ###
