export default {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/vue3-recommended',
    'eslint:recommended',
    '@vue/typescript/recommended',
    '@vue/prettier',
    '@vue/prettier/@typescript-eslint',
  ],
  parserOptions: {
    ecmaVersion: 2020,
  },
  rules: {
    'vue/no-unused-components': 'warn',
    'vue/no-unused-vars': 'warn',
    'vue/no-unsupported-features': 'warn',
    'vue/no-unsupported-vue-features': 'warn',
    'vue/no-potential-component-option-typo': 'warn',
    'vue/no-reserved-props': 'warn',
    'vue/no-reserved-keys': 'warn',
    'vue/no-useless-mustaches': 'warn',
    'vue/no-useless-v-bind': 'warn',
    'vue/no-useless-v-on': 'warn',
    'vue/no-useless-template-attributes': 'warn',
    'vue/no-v-html': 'warn',
    'vue/no-v-text-v-html-on-component': 'warn',
    'vue/no-v-model-argument': 'warn',
    'vue/no-v-model-props': 'warn',
    'vue/no-v-for-template-key': 'warn',
    'vue/no-v-for-template-key-on-child': 'warn',
    'vue/no-v-for-template-key': 'warn',
  },
};
