[project]
name = "server-flask"
version = "0.9.0"
description = "StaffSec"
requires-python = ">=3.12"
dependencies = [
    "blinker>=1.9.0",
    "click>=8.3.1",
    "flask>=3.1.2",
    "flask-compress>=1.23",
    "greenlet>=3.3.0",
    "gunicorn>=23.0.0",
    "itsdangerous>=2.2.0",
    "jinja2>=3.1.6",
    "markupsafe>=3.0.3",
    "orjson>=3.11.5",
    "psycopg2-binary>=2.9.11",
    "pydantic>=2.12.5",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.2.1",
    "sqlalchemy>=2.0.30",
    "typing-extensions>=4.15.0",
    "werkzeug>=3.1.4",
]

[dependency-groups]
dev = ["pytest>=9.0.2"]

[tool.ruff]
select = ["ALL"]
ignore = ["DTZ005", "RUF003", "RUF001", "PLR2004", "PLC0415"]

[tool.ruff.per-file-ignores]
"app/tests/*.py" = ["ALL"]

[tool.pytest.ini_options]
addopts = [
  "-vv",
  "--import-mode=importlib",
]
minversion = "9.0"
python_files = ["test_*.py", "*_test.py", "tests.py"]
python_functions = ["test_*"]
pythonpath = ["."]
testpaths = ["app/tests"]
