[project]
name = "server-flask"
version = "0.1.0"
description = "StaffSec"
requires-python = ">=3.12"
dependencies = [
    "blinker==1.8.2",
    "click==8.1.7",
    "flask==2.3.3",
    "greenlet==3.1.1",
    "gunicorn>=23.0.0",
    "itsdangerous==2.2.0",
    "jinja2==3.1.4",
    "markupsafe==3.0.1",
    "psutil==5.9.0",
    "pydantic==1.10.18",
    "pyjwt==2.8.0",
    "sqlalchemy==2.0.30",
    "typing-extensions==4.12.2",
    "werkzeug==3.0.4",
]

[dependency-groups]
dev = ["pytest>=9.0.1"]

[tool.ruff]
select = ["ALL"]
ignore = ["DTZ005", "RUF003", "RUF001", "PLR2004", "PLC0415"]

[tool.ruff.per-file-ignores]
"app/tests/*.py" = ["ALL"]

[tool.pytest.ini_options]
addopts = [
  "-vv",
  "--import-mode=importlib",
]
minversion = "9.0"
python_files = ["test_*.py", "*_test.py", "tests.py"]
python_functions = ["test_*"]
pythonpath = ["."]
testpaths = ["app/tests"]
